[target.riscv32imc-unknown-none-elf]
# Uncomment to run simulation
# runner = "./run-sim"
runner = "./run-bl"

rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=--nmagic"]

# neorv32 supports quite a few ISA extensions but good for dev to keep it minimal
[build]
target = "riscv32imc-unknown-none-elf"
